webtalk_init -webtalk_dir C:/Users/waitee/Documents/koodit/vivado/HDL_based_design/led_driver/led_driver.sim/sim_1/behav/xsim/xsim.dir/led_driver_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Nov  1 17:32:53 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "92ce6c4f-f98f-4757-bade-b9a805e89b8e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "670cd2598876441ba176d0778dcaee41" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "26" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "12072170 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.48_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "13668_KB" -context "xsim\\usage"
webtalk_transmit -clientid 999741516 -regid "" -xml C:/Users/waitee/Documents/koodit/vivado/HDL_based_design/led_driver/led_driver.sim/sim_1/behav/xsim/xsim.dir/led_driver_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/waitee/Documents/koodit/vivado/HDL_based_design/led_driver/led_driver.sim/sim_1/behav/xsim/xsim.dir/led_driver_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/waitee/Documents/koodit/vivado/HDL_based_design/led_driver/led_driver.sim/sim_1/behav/xsim/xsim.dir/led_driver_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
